name: sif_dong_li_2023_sample
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - blosc=1.21.6=he440d0b_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - freexl=2.0.0=h9dce30a_2
  - geos=3.14.1=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - giflib=5.2.2=hd590300_0
  - icu=75.1=he02047a_0
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.8.2=gpl_h7be2006_100
  - libblas=3.11.0=3_h4a7cf45_openblas
  - libcblas=3.11.0=3_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgdal-core=3.10.3=h1f481a6_27
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=he0feb66_14
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=3_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.51=h421ea60_0
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - minizip=4.0.10=h05a5f5f_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.5=py314h2b28147_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh145f28c_0
  - proj=9.7.1=h99ae125_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pystac=1.14.1=pyhd8ed1ab_0
  - python=3.14.0=h32b2ec7_103_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.14=8_cp314
  - rasterio=1.4.3=py314hab41f0e_3
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py314hbe3edd8_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=hbc0de68_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025b=h78e105d_0
  - uriparser=0.9.8=hac33072_0
  - xerces-c=3.3.0=h988505b_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=h3691f8a_5
